export const types={
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',
    AUTHENTICATE_ERROR:'AUTHENTICATE_ERROR',
    SEARCH_PLANETS:'SEARCH_PLANETS',
    SEARCH_PLANETS_SUCCESS:'SEARCH_PLANETS_SUCCESS',
    SEARCH_PLANETS_ERROR:'SEARCH_PLANETS_ERROR',
    RESET_PLANETS:'RESET_PLANETS',
    GET_PLANET_INFO: 'GET_PLANET_INFO',
    PLANET_DETAILS_SUCCESS: 'PLANET_DETAILS_SUCCESS',
    PLANET_DETAILS_ERROR:'PLANET_DETAILS_ERROR',
};