export const types={
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',
    AUTHENTICATE_ERROR:'AUTHENTICATE_ERROR',
    SEARCH_PLANETS:'SEARCH_PLANETS',
    SEARCH_PLANETS_SUCCESS:'SEARCH_PLANET_SUCCESS',
    SEARCH_PLANETS_ERROR:'SEARCH_PLANET_ERROR',
};