export const types={
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR:'LOGIN_ERROR',
    SEARCH_PLANETS:'SEARCH_PLANETS',
    SEARCH_PLANETS_SUCCESS:'SEARCH_PLANETS_SUCCESS',
    SEARCH_PLANETS_ERROR:'SEARCH_PLANETS_ERROR',
    RESET_PLANETS:'RESET_PLANETS',
    GET_PLANET_INFO: 'GET_PLANET_INFO',
    PLANET_DETAILS_SUCCESS: 'PLANET_DETAILS_SUCCESS',
    PLANET_DETAILS_ERROR:'PLANET_DETAILS_ERROR',
};